### ISSUE TITLE
转换链接失败

### ISSUE THREAD

**Issue by zgl018** [silently9527/mall-coupons-server#11]
申请了pid绑定到了大淘客
但是点进单品有时还是会转换链接失败, body:{"requestId":"ba25c7b1701aed8bf839b883f37d756b","time":1613729205514,"code":10066,"msg":"请检查site_id和adzone_id是否匹配"}

**Comment by zgl018** [comment]
https://www.dataoke.com/pmc/pid-manager.html
pid渠道和用途填哪一种

**Comment by zgl018** [comment]
不好意思，才看到代码里PrivilegeApi.class里的pid
忘记改了

**Comment by zgl018** [comment]
建议把pid放到配置文件里

**Comment by silently9527** [comment]
@zgl018 你有空的话，帮忙修改一下，把pid放到配置文件里，提交一个分支合并；最近加班太多了
