### ISSUE TITLE
java -jar mall-coupons-server-0.0.1-SNAPSHOT.jar  --spring.profiles.active=prod &运行失败

### ISSUE THREAD

**Issue by xiaolei000129** [silently9527/mall-coupons-server#14]
com.huaan9527.mall.webapi.controller中构造函数的参数3。PublicController需要一个类型为'org.springframework.data.redis.core '的bean。RedisTemplate'无法找到。
找到了下列候选人，但无法注射:
- 'RedisAutoConfiguration'中的Bean方法'redisTemplate'没有加载，因为@ConditionalOnMissingBean (names: redisTemplate;SearchStrategy: all)发现名为redisTemplate的bean

**Comment by silently9527** [comment]
把RedisTemplate的泛型去掉试试看可以不
