### ISSUE TITLE
本地运行显示找不到主类

### ISSUE THREAD

**Issue by xiaolei000129** [silently9527/mall-coupons-server#15]
![image](https://user-images.githubusercontent.com/44334120/116645161-c7b39600-a9a7-11eb-9a6d-48ced1dd7983.png)

**Comment by silently9527** [comment]
![image](https://user-images.githubusercontent.com/5729336/116645426-6dff9b80-a9a8-11eb-9204-488976d9482d.png)

**Comment by xiaolei000129** [comment]
![image](https://user-images.githubusercontent.com/44334120/116645555-af904680-a9a8-11eb-9d27-f68198a8a70a.png)
没有这个选项

**Comment by silently9527** [comment]
![image](https://user-images.githubusercontent.com/5729336/116645903-6260a480-a9a9-11eb-8d8c-9d063758b28d.png)
你这中文版的  我有点搞不懂了
