### ISSUE TITLE
启动直接错，找不到：org.springframework.social.* 下的对象

### ISSUE THREAD

**Issue by happytsgf** [silently9527/mall-coupons-server#2]
是不是还有某个dependency没有引入吗？

**Comment by silently9527** [comment]
你更新下代码    昨天已经更新了pom.xml   把一些依赖放入到了lib

**Comment by happytsgf** [comment]
> 你更新下代码 昨天已经更新了pom.xml 把一些依赖放入到了lib

好的，明白了，这个lib单独添加在编译里。 
在lib里的，没办法在仓库引用的吗？

**Comment by happytsgf** [comment]
还是提示：程序包org.springframework.social.connect不存在
