### ISSUE TITLE
RedisTemplate  启动项目报错啊

### ISSUE THREAD

**Issue by commanding** [silently9527/mall-coupons-server#6]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of constructor in com.huaan9527.mall.webapi.controller.PublicController required a bean of type 'org.springframework.data.redis.core.RedisTemplate' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'redisTemplate' in 'RedisAutoConfiguration' not loaded because @ConditionalOnMissingBean (names: redisTemplate; SearchStrategy: all) found beans named redisTemplate

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.data.redis.core.RedisTemplate' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:65469', transport: 'socket'

**Comment by commanding** [comment]
已解决

**Comment by jsrgqinbin** [comment]
怎么解决的，同样的报错
